name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  semantic:
    uses: ./.github/workflows/semantic-release.yml
    secrets:
      gh_token: ${{ secrets.GH_RELEASE_PAT }}

  docker-build-and-push:
    needs: semantic
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      version: ${{ needs.semantic.outputs.new_version }}
      commit_sha: ${{ github.sha }}
      architectures: >
      [
        {"os":"linux","arch":"amd64"},
        {"os":"linux","arch":"arm64"},
        {"os":"linux","arch":"arm","goarm":"7"}
      ]
    secrets:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-binaries:
    needs: semantic
    uses: ./.github/workflows/binaries.yml
    with:
      version: ${{ needs.semantic.outputs.new_version }}
      commit_sha: ${{ github.sha }}
      architectures: >
        [
          {"os":"linux","arch":"amd64"},
          {"os":"linux","arch":"arm64"},
          {"os":"linux","arch":"arm","goarm":"7"}
        ]

  attach-binaries-to-release:
    needs: binaries
    runs-on: ubuntu-latest
    steps:
      - name: Download all binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: obfs-exporter-*
          merge-multiple: true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.semantic.outputs.new_version }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
