name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    container:
      image: docker.io/plushguardian/semantic-release-for-ci:1.0.1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mark workspace as Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        run: npx semantic-release
