name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: docker.io/plushguardian/semantic-release-for-ci:1.0.1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
